# Generated by Django 4.2 on 2023-10-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="changeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("SSID", models.CharField(max_length=100)),
                ("eventType", models.CharField(max_length=100)),
                ("page", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("admin", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="deviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Access Date")),
                ("deviceID", models.CharField(max_length=100)),
                ("deviceType", models.CharField(max_length=100)),
                ("SSID", models.CharField(max_length=100)),
                ("clientType", models.CharField(max_length=100)),
                ("clientIP", models.CharField(max_length=100)),
                ("eventType", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="logFileUnfiltered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("subType", models.CharField(max_length=100)),
                ("eventID", models.CharField(max_length=100, unique=True)),
                ("eventTitle", models.CharField(max_length=100)),
                ("priority", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=100)),
                ("details2", models.CharField(max_length=100)),
                ("JSON", models.CharField(max_length=100)),
                ("JSON2", models.CharField(max_length=100)),
                ("clientTimelineTitle", models.CharField(max_length=100)),
                ("APPdestination", models.CharField(max_length=100)),
                ("AlertLicense", models.CharField(max_length=100)),
                ("ESIndex", models.CharField(max_length=100)),
                ("APAlertLicenseBasic", models.CharField(max_length=100)),
                ("APAlertLicensePro", models.CharField(max_length=100)),
                ("APAlertLicenseProV", models.CharField(max_length=100)),
                ("APAlertLicenseProR", models.CharField(max_length=100)),
                ("switchAlertLicenseBasic", models.CharField(max_length=100)),
                ("switchAlertLicensePro", models.CharField(max_length=100)),
                ("switchAlertLicenseProV", models.CharField(max_length=100)),
                ("switchAlertLicenseProR", models.CharField(max_length=100)),
                ("GatewayAlertLicenseBasic", models.CharField(max_length=100)),
                ("GatewayAlertLicensePro", models.CharField(max_length=100)),
                ("GatewayAlertLicenseProV", models.CharField(max_length=100)),
                ("GatewayAlertLicenseProR", models.CharField(max_length=100)),
                ("PDUAlertLicenseBasic", models.CharField(max_length=100)),
                ("PDUAlertLicensePro", models.CharField(max_length=100)),
                ("PDUAlertLicenseProV", models.CharField(max_length=100)),
                ("PDUAlertLicenseProR", models.CharField(max_length=100)),
                ("SwitchExtenderAlertLicensePro", models.CharField(max_length=100)),
                ("GatewayAlertLicenseSPC", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="systemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("eventType", models.CharField(max_length=100)),
                ("target", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("admin", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TextLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("subType", models.CharField(max_length=100)),
                ("eventID", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
