# Generated by Django 4.2 on 2023-10-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textlogs",
            name="eventTitle",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
