# Generated by Django 4.2 on 2023-10-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_textlogs_eventtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textlogs",
            name="eventID",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="textlogs",
            name="eventTitle",
            field=models.CharField(max_length=100),
        ),
    ]
